application:
  name: ab-ecom
  service: ab-ecom-mail

info:
  app:
    name: ${application.service}
    description: Application to manage mail API
    version: 1.0

mail:
  toemail: anirudhb2b@gmail.com
  fromemail: anirudhb2b@gmail.com
  environment: Local
  companies:
    -
      id: 1
      name: COMPANY1
      email: company1support@gmail.com
    -
      id: 2
      name: COMPANY2
      email: company2support@gmail.com
    -
      id: 3
      name: COMPANY3
      email: company3support@gmail.com
  timesheets:
    -
      id: 1
      name: Vendor
    -
      id: 2
      name: Partner
    -
      id: 3
      name: Client

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      wavefront:
        api-token: 1c28ac31-cfb3-4574-aef9-61d0afac7379
        enabled: true
        uri: https://wavefront.surf

server:
  port: 8084

spring:
  application:
    name: ${application.service}
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: true
          ssl:
            enable: false
            trust: smtp.gmail.com
      debug: false
    username: anirudhb2b@gmail.com
    password: snsdqdiqthxvkxsw
  security:
    user:
      name: admin
      password: admin

wavefront:
  application:
    name: ${application.name}
    service: ${application.service}
